from selenium.webdriver.common.by import By


class LoginPageLocators:
    USER_NAME = (By.CSS_SELECTOR, "#username")
    USER_PASSWORD = (By.CSS_SELECTOR, "#login")
    CONFIRM_BUTTON = (By.CSS_SELECTOR, ".action-login")


class BasePageLocators:
    EBAY_LINK = (By.CSS_SELECTOR, "#menu-ess-m2epro-ebay>a")
    AMAZON_LINK = (By.CSS_SELECTOR, "#menu-ess-m2epro-amazon>a")
    WALMART_LINK = (By.CSS_SELECTOR, "#menu-ess-m2epro-walmart>a")
    PROGRESS_BAR_PERCENTAGE = (By.CSS_SELECTOR, "#marketplaces_progress_bar_percents")
    EBAY_POLICIES_PAGE = (By.CSS_SELECTOR, ".item-ebay-configuration-templates ")
    SUCCESS_MESSAGE = (By.CSS_SELECTOR, "[data-ui-id='messages-message-success']")


class WizardFirstStepLocators:
    OK_BUTTON = (By.CSS_SELECTOR, ".action.primary")
    EMAIL = (By.CSS_SELECTOR, "#form_email")
    FIRST_NAME = (By.CSS_SELECTOR, "#first_name")
    LAST_NAME = (By.CSS_SELECTOR, "#last_name")
    PHONE = (By.CSS_SELECTOR, "#phone")
    COUNTRY = (By.CSS_SELECTOR, "#country")
    CITY = (By.CSS_SELECTOR, "#city")
    POSTAL_CODE = (By.CSS_SELECTOR, "#postal_code")
    CHECK = (By.CSS_SELECTOR, "#licence_agreement")
    CONTINUE = (By.CSS_SELECTOR, "#continue")


class EbayWizardLocators:
    SANDBOX_MODE = (By.CSS_SELECTOR, "#modesandbox")
    CONTINUE = (By.CSS_SELECTOR, "#continue")
    EBAY_USERNAME = (By.CSS_SELECTOR, "#userid")
    EBAY_PASSWORD = (By.CSS_SELECTOR, "#pass")
    SIGN_IN_BUTTON = (By.CSS_SELECTOR, "#sgnBt")
    SUBMIT_BUTTON = (By.CSS_SELECTOR, "#submit")
    UPC = (By.CSS_SELECTOR, "#product_identifier_upc")
    EAN = (By.CSS_SELECTOR, "#product_identifier_ean")
    LABEL = (By.CSS_SELECTOR, "#store_label")
    CODE = (By.CSS_SELECTOR, "#code")
    CONFIRM = (By.CSS_SELECTOR, ".action.primary")
    SKIP = (By.CSS_SELECTOR, "#skip")
    NEXT_STEP = (By.CSS_SELECTOR, "#signin-continue-btn")


class EbayMarketplaceUpdatePageLocators:
    MARKETPLACES_PAGE = (By.CSS_SELECTOR, ".item-ebay-configuration-marketplaces")
    SYNCHRONIZATION_COMPLETED = (By.XPATH, "//div[text() = 'Marketplace synchronization was completed.']")

    UNITED_STATES = (By.CSS_SELECTOR, "#status_1")
    CANADA = (By.CSS_SELECTOR, "#status_2")
    CANADA_FRENCH = (By.CSS_SELECTOR, "#status_19")
    UNITED_KINGDOM = (By.CSS_SELECTOR, "#status_3")
    GERMANY = (By.CSS_SELECTOR, "#status_8")
    AUSTRIA = (By.CSS_SELECTOR, "#status_5")
    BELGIUM_DUTCH = (By.CSS_SELECTOR, "#status_11")
    BELGIUM_FRENCH = (By.CSS_SELECTOR, "#status_6")
    FRANCE = (By.CSS_SELECTOR, "#status_7")
    IRELAND = (By.CSS_SELECTOR, "#status_17")
    ITALY = (By.CSS_SELECTOR, "#status_10")
    NETHERLANDS = (By.CSS_SELECTOR, "#status_12")
    POLAND = (By.CSS_SELECTOR, "#status_21")
    SPAIN = (By.CSS_SELECTOR, "#status_13")
    SWITZERLAND = (By.CSS_SELECTOR, "#status_14")
    AUSTRALIA = (By.CSS_SELECTOR, "#status_4")
    HONG_KONG = (By.CSS_SELECTOR, "#status_15")
    INDIA = (By.CSS_SELECTOR, "#status_16")
    MALAYSIA = (By.CSS_SELECTOR, "#status_18")
    PHILIPPINES = (By.CSS_SELECTOR, "#status_20")
    SINGAPORE = (By.CSS_SELECTOR, "#status_22")
    EBAY_MOTORS = (By.CSS_SELECTOR, "#status_9")
    SAVE = (By.CSS_SELECTOR, "#run_save_and_synch")
    UPDATE_ALL = (By.CSS_SELECTOR, "#run_update_all")

    UNITED_STATES_ENABLED = (By.CSS_SELECTOR, "#status_1 > [value = '1']")
    CANADA_ENABLED = (By.CSS_SELECTOR, "#status_2 > [value = '1']")
    CANADA_FRENCH_ENABLED = (By.CSS_SELECTOR, "#status_19 > [value = '1']")
    UNITED_KINGDOM_ENABLED = (By.CSS_SELECTOR, "#status_3 > [value = '1']")
    GERMANY_ENABLED = (By.CSS_SELECTOR, "#status_8 > [value = '1']")
    AUSTRIA_ENABLED = (By.CSS_SELECTOR, "#status_5 > [value = '1']")
    BELGIUM_DUTCH_ENABLED = (By.CSS_SELECTOR, "#status_11 > [value = '1']")
    BELGIUM_FRENCH_ENABLED = (By.CSS_SELECTOR, "#status_6 > [value = '1']")
    FRANCE_ENABLED = (By.CSS_SELECTOR, "#status_7 > [value = '1']")
    IRELAND_ENABLED = (By.CSS_SELECTOR, "#status_17 > [value = '1']")
    ITALY_ENABLED = (By.CSS_SELECTOR, "#status_10 > [value = '1']")
    NETHERLANDS_ENABLED = (By.CSS_SELECTOR, "#status_12 > [value = '1']")
    POLAND_ENABLED = (By.CSS_SELECTOR, "#status_21 > [value = '1']")
    SPAIN_ENABLED = (By.CSS_SELECTOR, "#status_13 > [value = '1']")
    SWITZERLAND_ENABLED = (By.CSS_SELECTOR, "#status_14 > [value = '1']")
    AUSTRALIA_ENABLED = (By.CSS_SELECTOR, "#status_4 > [value = '1']")
    HONG_KONG_ENABLED = (By.CSS_SELECTOR, "#status_15 > [value = '1']")
    INDIA_ENABLED = (By.CSS_SELECTOR, "#status_16 > [value = '1']")
    MALAYSIA_ENABLED = (By.CSS_SELECTOR, "#status_18 > [value = '1']")
    PHILIPPINES_ENABLED = (By.CSS_SELECTOR, "#status_20 > [value = '1']")
    SINGAPORE_ENABLED = (By.CSS_SELECTOR, "#status_22 > [value = '1']")
    EBAY_MOTORS_ENABLED = (By.CSS_SELECTOR, "#status_9 > [value = '1']")

    # UNITED_STATES_COMPLETED = (By.CSS_SELECTOR, "#synch_info_complete_1")
    # CANADA_COMPLETED = (By.CSS_SELECTOR, "#synch_info_complete_2")
    # CANADA_FRENCH_COMPLETED = (By.CSS_SELECTOR, "#synch_info_complete_19")
    # UNITED_KINGDOM_COMPLETED = (By.CSS_SELECTOR, "#synch_info_complete_3")
    # GERMANY_COMPLETED = (By.CSS_SELECTOR, "#synch_info_complete_8")
    # AUSTRIA_COMPLETED = (By.CSS_SELECTOR, "#synch_info_complete_5")
    # BELGIUM_DUTCH_COMPLETED = (By.CSS_SELECTOR, "#synch_info_complete_11")
    # BELGIUM_FRENCH_COMPLETED = (By.CSS_SELECTOR, "#synch_info_complete_6")
    # FRANCE_COMPLETED = (By.CSS_SELECTOR, "#synch_info_complete_7")
    # IRELAND_COMPLETED = (By.CSS_SELECTOR, "#synch_info_complete_17")
    # ITALY_COMPLETED = (By.CSS_SELECTOR, "#synch_info_complete_10")
    # NETHERLANDS_COMPLETED = (By.CSS_SELECTOR, "#synch_info_complete_12")
    # POLAND_COMPLETED = (By.CSS_SELECTOR, "#synch_info_complete_21")
    # SPAIN_COMPLETED = (By.CSS_SELECTOR, "#synch_info_complete_13")
    # SWITZERLAND_COMPLETED = (By.CSS_SELECTOR, "#synch_info_complete_14")
    # AUSTRALIA_COMPLETED = (By.CSS_SELECTOR, "#synch_info_complete_4")
    # HONG_KONG_COMPLETED = (By.CSS_SELECTOR, "#synch_info_complete_15")
    # INDIA_COMPLETED = (By.CSS_SELECTOR, "#synch_info_complete_16")
    # MALAYSIA_COMPLETED = (By.CSS_SELECTOR, "#synch_info_complete_18")
    # PHILIPPINES_COMPLETED = (By.CSS_SELECTOR, "#synch_info_complete_20")
    # SINGAPORE_COMPLETED = (By.CSS_SELECTOR, "#synch_info_complete_22")
    # EBAY_MOTORS_COMPLETED = (By.CSS_SELECTOR, "#synch_info_complete_9")


class PoliciesPageLocators:
    ADD_BUTTON = (By.CSS_SELECTOR, ".add")
    ADD_SHIPPING_POLICY = (By.CSS_SELECTOR, "#add_policy-shipping")


class EbayShippingPolicyLocators:
    TITLE = (By.CSS_SELECTOR, "#title")
    US_MARKETPLACE = (By.CSS_SELECTOR, "#marketplace_id")
    ADD_SHIPPING_METHOD_BUTTON = (By.CSS_SELECTOR, "#add_local_shipping_method>.add")
    SHIPPING_SERVICE = (By.CSS_SELECTOR, ".shipping-service")
    ITEM_LOCATION_TAB = (By.CSS_SELECTOR, ".admin__collapsible-title")
    COST = (By.CSS_SELECTOR, ".cost-mode")
    SAVE_AND_CONTINUE_BUTTON = (By.CSS_SELECTOR, "#save_and_continue-button")
